# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='acc_now_delinq',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='addr_state',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='annual_inc',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='application_type',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='batch_enrolled',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='collection_recovery_fee',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='collections_12_mths_ex_med',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='delinq_2yrs',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='desc',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='dti',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='emp_length',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='emp_title',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='funded_amnt',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='funded_amnt_inv',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='grade',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='home_ownership',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='initial_list_status',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='inq_last_6mths',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='int_rate',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='last_week_pay',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='loan_amnt',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='loan_status',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='member_id',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='mths_since_last_delinq',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='mths_since_last_major_derog',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='mths_since_last_record',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='open_acc',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='pub_rec',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='purpose',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='pymnt_plan',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='recoveries',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='revol_bal',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='revol_util',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='sub_grade',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='term',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='title',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='tot_coll_amt',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='tot_cur_bal',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='total_acc',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='total_rec_int',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='total_rec_late_fee',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='total_rev_hi_lim',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='verification_status',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='verification_status_joint',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='zip_code',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
    ]
