# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-30 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191130_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='desc',
            field=models.TextField(),
        ),
    ]
