# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191209_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='verification_status',
            field=models.CharField(max_length=9),
        ),
    ]
