# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191209_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='addr_state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='delinq_2yrs',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='dti',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='inq_last_6mths',
            field=models.CharField(max_length=2),
        ),
    ]
