# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191209_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=8)),
                ('loan_amnt', models.CharField(max_length=5)),
                ('funded_amnt', models.CharField(max_length=5)),
                ('funded_amnt_inv', models.CharField(max_length=18)),
                ('term', models.CharField(max_length=9)),
                ('batch_enrolled', models.CharField(max_length=10)),
                ('int_rate', models.CharField(max_length=5)),
                ('grade', models.CharField(max_length=1)),
                ('sub_grade', models.CharField(max_length=2)),
                ('emp_title', models.TextField()),
                ('emp_length', models.CharField(max_length=9)),
                ('home_ownership', models.CharField(max_length=8)),
                ('annual_inc', models.CharField(max_length=9)),
                ('verification_status', models.CharField(max_length=15)),
                ('pymnt_plan', models.CharField(max_length=1)),
                ('desc', models.TextField()),
                ('purpose', models.CharField(max_length=18)),
                ('title', models.TextField()),
                ('zip_code', models.CharField(max_length=5)),
                ('addr_state', models.CharField(max_length=2)),
                ('dti', models.CharField(max_length=5)),
                ('delinq_2yrs', models.CharField(max_length=2)),
                ('inq_last_6mths', models.CharField(max_length=2)),
                ('mths_since_last_delinq', models.CharField(max_length=5)),
                ('mths_since_last_record', models.CharField(max_length=5)),
                ('open_acc', models.CharField(max_length=2)),
                ('pub_rec', models.CharField(max_length=2)),
                ('revol_bal', models.CharField(max_length=7)),
                ('revol_util', models.CharField(max_length=5)),
                ('total_acc', models.CharField(max_length=3)),
                ('initial_list_status', models.CharField(max_length=1)),
                ('total_rec_int', models.CharField(max_length=8)),
                ('total_rec_late_fee', models.CharField(max_length=18)),
                ('recoveries', models.CharField(max_length=8)),
                ('collection_recovery_fee', models.CharField(max_length=19)),
                ('collections_12_mths_ex_med', models.CharField(max_length=3)),
                ('mths_since_last_major_derog', models.CharField(max_length=5)),
                ('application_type', models.CharField(max_length=10)),
                ('verification_status_joint', models.CharField(max_length=15)),
                ('last_week_pay', models.CharField(max_length=10)),
                ('acc_now_delinq', models.CharField(max_length=1)),
                ('tot_coll_amt', models.CharField(max_length=7)),
                ('tot_cur_bal', models.CharField(max_length=9)),
                ('total_rev_hi_lim', models.CharField(max_length=9)),
                ('loan_status', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='CsvFile',
        ),
    ]
