# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191209_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='purpose',
            field=models.TextField(),
        ),
    ]
