# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191209_0753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CsvFile',
            new_name='CsvFile1',
        ),
    ]
