# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
