# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20191209_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=100)),
            ],
        ),
    ]
