# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelname',
            name='test',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
